name: Test building

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev
          
      - name: Correcting NuGet package versions
        run: |
          sudo apt purge dotnet-*
          sudo rm -Rf /usr/share/dotnet
        
      - name: Initialize offline package
        run: |
          sudo ip netns add no-net
          chmod +x initializeoffline.sh
          ./initializeoffline.sh
        
      - name: Try to build
        run: sudo ip netns exec no-net ./roslyn/build.sh --restore --configuration Release
